version: '3'

services:
    php_test:
        image: everytimeicob/php:8.1-fpm
        container_name: php_test
        restart: 'no'
        ports:
            - '9001:9000'
        environment:
            APP_ENV: test
        volumes:
            - ./:/var/www/html/

    postgres_test:
        image: postgres:14-alpine
        container_name: postgres_test
        restart: 'no'
        environment:
            POSTGRES_DB: recipe
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        expose:
            - 5431
        ports:
            - '5431:5432'
        volumes:
            - ./infra/docker/postgres/:/home

    aws_test:
        build:
            context: infra/docker/localstack
        container_name: aws_test
        environment:
            SERVICES: sqs
#            EDGE_BIND_HOST: 0.0.0.0
#            EDGE_PORT: 4566
#            HOSTNAME: localhost
#            HOSTNAME_EXTERNAL: localhost
#            SQS_PORT_EXTERNAL: 4567
            USE_LIGHT_IMAGE: 1
            LS_LOG: info
            AWS_REGION: eu-central-1
            AWS_ACCESS_KEY_ID: local
            AWS_SECRET_ACCESS_KEY: local
            DOCKER_SOCK: unix:///var/run/docker.sock
            DOCKER_CMD: docker
        ports:
            - '4567:4566'
