imports:
    - { resource: domain.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Recipe\Infrastructure\Bus\MessengerCommandBus: ~

    Recipe\Infrastructure\Fixture\RecipeFixtures: ~

    Recipe\Infrastructure\Persistence\Repository\RepositoryFactory: ~
    Recipe\Infrastructure\Projector\Recipe\GetARecipeOrmProjector: ~

    Recipe\Infrastructure\Query\DbalRecipeReadModelRepository: ~

    Ramsey\Uuid\UuidFactory: ~
    Ramsey\Uuid\UuidFactoryInterface: '@Ramsey\Uuid\UuidFactory'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
            public: true

        Recipe\Domain\Bus\CommandBus:
            alias: Recipe\Infrastructure\Bus\MessengerCommandBus

        Ramsey\Uuid\UuidFactoryInterface:
            alias: Ramsey\Uuid\UuidFactory

        Recipe\Infrastructure\Projector\Recipe\GetARecipeOrmProjector: ~
